### ISSUE TITLE
Calendar is not synced with Iteration capacity

### ISSUE THREAD

**Issue by florinangelescu** [microsoft/vsts-team-calendar#240]
Hello,

Even though I have filled in days off in the Calendar section in Azure DevOps, these days are not included in the availability from the Iteration Planning.

And vice-versa. These two functionalities should be connected, otherwise I don't see the purpose of the Calendar if we have to fill in days off in two different places.

**Comment by CoolDadTx** [comment]
This may be related to what we're seeing. The issue we see is that the calendar does not properly put days off in capacity for an iteration if the days off cross iterations. When you add days off under iterations it won't let you put dates outside the range of the iteration. So if you are taking days off across iterations you have to put it the appropriate days under each iteration individually.

On the calendar you can put dates that cross iterations. However it doesn't record the days off for the second iteration. It seems to be treating all the days off as though they are part of the first iteration, which isn't allowed via the UI at least. We noticed this when we started a new sprint and folks who weren't here (because the calendar said they were off) had 0 days off under Capacity. When we added their days off to Capacity then the calendar showed them being off twice on the overlapping days. We had to go into the calendar and fix the dates of the original event so it didn't overlap and then capacity seemed to be correct.

**Comment by roberto-orsted** [comment]
is there a plan to address this issue?

**Comment by ruturaj-h** [comment]
The newer version which is published for hosted version will allow only days off from single iteration.
