### ISSUE TITLE
Some events not shown in Firefox (Chrome works fine)

### ISSUE THREAD

**Issue by jeroenhabets** [microsoft/vsts-team-calendar#318]
I have added duplicates of the same event (within sprint boundaries) because they disappear after closing the window in Firefox 80.0.1 (64-bit).

The duplicates do appear in Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by acarrau** [comment]
Having same problem, in Edge as well. 

In Firefox 79 and Microsoft Edge 42.17134.1098.0, after adding an event and refreshing, the event disappears.

Workaround: Click "Next" and "Prev". All "missing" event appears again.

**Comment by chrisgdg** [comment]
We also have a user having this issue. As acarrau has said above (Thanks for that), a workaround is to click on Next or Prev, and the events then show again.
It happens for the user no matter what browser they use (They are using a MacBook Pro, and have tried Chrome, Firefox and Safari).
They've also tried on their iPhone, and have the same issue, so seems to be related to their account, as no other users have reported the issue.

**Comment by carlo-sc** [comment]
hi all, we have the same problem (tested with the last versions of these browsers: edge, firefox, chrome).
Right now, I'm using the same workaround <PREV NEXT> in order to refresh the page and see all the events recently added.
This bug is very recent because the extension was working fine just two weeks ago.
there is any fix scheduled? i'm available if you need support to reproduce the issue.
thanks 
carlo
