### ISSUE TITLE
Cannot add days off on May 6th!

### ISSUE THREAD

**Issue by Panksy** [Microsoft/vsts-team-calendar#35]
I don't know if this something to do with this being a holiday day in the USA but we are unable to add Days off on May 6th.

![image](https://cloud.githubusercontent.com/assets/5558648/14520457/e92169be-0224-11e6-81a5-b202e97e486d.png)

I probably should add that we are using this through visual studio online

**Comment by Panksy** [comment]
Hi, We just worked out that this day is not within a sprint so I don't believe its a bug - however it does mean that we can not use it for out of office days w

**Comment by hajohns** [comment]
You should now be able to add a day off any day, within or outside of a sprint, by linking it to a sprint in the add dialog. If you want to create a day off event independent sprints, it would probably be better as a freeform event, since days off are used to calculate capacity for a sprint. Hope that helps!
