### ISSUE TITLE
Calendar synchronisation issues.

### ISSUE THREAD

**Issue by BelindedeBoer** [microsoft/vsts-team-calendar#440]
After entering new events or days off it seems it not always synchronized. When you open it again, a new entry has disappeared but when you click on the next and prev button it all of the sudden shows again. [](url)
![start opening the calendar](https://user-images.githubusercontent.com/124793612/217541203-4516053c-5952-4154-b4da-51c3c18d26c6.PNG)
![result after using the next- prev button](https://user-images.githubusercontent.com/124793612/217541228-c6d10ea4-4c76-4755-afad-669d2c0931ad.PNG)

**Comment by DevFlake** [comment]
We had that issue for a few weeks, but the entries appeared again after clicking forward and backward (or vv). But suddenly the didn't come back :-)
We can add an event, but after refreshing the website the entry disappears...

**Comment by JJKW1984** [comment]
We have this same issue occurring in our environment. Version 2.0.16 (Latest)

**Comment by AminTi** [comment]
Thanks for reporting. it will be fixed in an upcoming release.

**Comment by BelindedeBoer** [comment]
Hi AminTi, when is the upcoming release to be expected?

**Comment by AminTi** [comment]
Hi!, I'm working on another extension but I will prioritize this issue this week or next week.

**Comment by JGPease** [comment]
We see the same issue. Glad it is being looked at. Thanks!

**Comment by Psysoul** [comment]
Hello Aminti!

This issue is not fixed on - 2.0.17.
However, I recognized something:
The issue only happens for "events" that are "uncategorized"
So at pageload time: uncategorized events are not shown.
Clicking next and previous: uncategorized events are shown correctly.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/87698073/221597576-a94ee323-eb0f-45a1-aa0b-5ae357582009.png">

Please let us know when this could be fixed!

Thank you in advance!

**Comment by MOlausson** [comment]
All, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by MOlausson** [comment]
We believe this has been resolved so closing this for now.
