### ISSUE TITLE
Doesn't work with Stakeholder licence?

### ISSUE THREAD

**Issue by trish1400** [microsoft/vsts-team-calendar#46]
We've installed this calendar for the purpose of sharing significant dates with our client, however if I log in as a client user (who has a Stakeholder licence) they don't seem to be able to view the calendar.

![image](https://cloud.githubusercontent.com/assets/1134522/14821398/81d88eac-0bc2-11e6-9438-1dd643f24e94.png)
N.B. the Learn More link goes to http://tfs:8080/items/ms-devlabs.team-calendar which obviously doesn't work for an external client. 

I've tried messing around with the permissions but I don't seem to be able to grant them anything that makes it work - the fact they also don't appear to have access to the Capacity tab on an iteration makes me suspect nothing will.  

Is there something I can change to fix this or is this a limitation of the Stakeholder licence?

Thanks.

**Comment by hajohns** [comment]
@trish1400 Can you email me directly at hajohns@microsoft.com with any script or network errors you're seeing on the page (or none if there are none)? Thank you.

**Comment by Rubbler** [comment]
We're having the same issue with Team Services.  Any stakeholders cannot save days off or events.  It allows them to open a dialog, and when they click save it goes away as if it saves the event but it never appears on the calendar.

**Comment by willsmythe** [comment]
@hajohns - as a first step, we shouldn't close the dialog until we've confirmed the add/update happened successfully (and we should present any error(s) to the user). We should then figure out why add/update of a free-form event isn't working for stakeholders (it should). Stakeholders can likely not set days off since days off are managed within the Work/Agile area (and are used for planning, etc).
