### ISSUE TITLE
Days off are calculated based on number of entries rather than total days

### ISSUE THREAD

**Issue by kriscremers** [microsoft/vsts-team-calendar#71]
Instead of calculating the total days over a range, it considers a range entry as 1 day off. 

The attached screenshot shows the problem. Person "BR" should have 7 days off instead of only 3. The 5 consecutive days in week 26 are entered as a range, so it considers it only 1 day.

![capture](https://cloud.githubusercontent.com/assets/16308286/16224655/41b6c6f6-37a3-11e6-96af-20bd0ab52bad.PNG)

**Comment by hajohns** [comment]
What version of Team Calendar do you have installed?

**Comment by Fluwit** [comment]
That'd be version 0.3.18. Installed directly from the Visual Studio Marketplace.

**Comment by hajohns** [comment]
There's clearly something not working right here, but I'm not sure what it is; the calendar is not using number of entries to calculate days off, it's using the range of days, and appears to be working for other members of the team (assuming WL added a 23 day block and not 23 separate entries). Does the capacities tab show the correct number of days off for "BR"?

Thank you for your help!

**Comment by Fluwit** [comment]
The capacities tab in the iteration itself shows the correct number of days off, yes.

I can reproduce it too. WL has a range that totals 23 days off. However, if I add a separate day off outside of that range, the sum of days off in the tab on the side shows 2 instead of 24. The same happens when I add days off for myself (KC), single days sum up fine, a single range works too, but the combination of single days and a range produces an incorrect total.

**Comment by stevchin** [comment]
Seeing this issue as well.  I first added a single day and then a range over 5 days, and it counted it as 2 days instead of 6 days.
