### ISSUE TITLE
Team member images not displayed

### ISSUE THREAD

**Issue by michael-damatov** [microsoft/vsts-team-calendar#81]
reproducible with FireFox v47 and v48

**Comment by willsmythe** [comment]
Not seeing this issue. @dmarcey - can you attempt to recreate?

**Comment by michael-damatov** [comment]
![image](https://cloud.githubusercontent.com/assets/11958365/17717817/6cc24e26-6410-11e6-9292-4f2f4f5a7c5b.png)

**Comment by willsmythe** [comment]
Can you copy one of the broken image urls and include in the issue? Feel free to omit your VSTS account name or any other identifying parts.
Will

Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Michael Damatov <notifications@github.com> Date: 8/16/16  6:20 PM  (GMT-05:00) To: Microsoft/vsts-team-calendar <vsts-team-calendar@noreply.github.com> Cc: Will Smythe <will.smythe@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Microsoft/vsts-team-calendar] Team member images not displayed
  (#81) 


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vsts-team-calendar","title":"Microsoft/vsts-team-calendar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vsts-team-calendar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@michael-damatov in #81: ![image](https://cloud.githubusercontent.com/assets/11958365/17717817/6cc24e26-6410-11e6-9292-4f2f4f5a7c5b.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vsts-team-calendar/issues/81#issuecomment-240257860"}}}

**Comment by Dan-Co** [comment]
Hello, we are and have been getting this as well for a long time.
We have an AAD backed VSTS instance with conditional access.
May be part of the problem.
Even just a fallback icon would work rather than the broken link icon.
Using Chrome 60+

**Comment by Chan-987** [comment]
We have the same here. I see an image broken icon for all links.. but when i click on it, i can see the avatar of the member. Something about security on ADD? I uninstall Calendar et re install it but no changes.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
