### ISSUE TITLE
Team Calendar by Microsoft DevLabs is taking longer than expected to load.Learn More about this extension, including available support options.

### ISSUE THREAD

**Issue by gangsir** [microsoft/vsts-team-calendar#85]
Team Calendar by Microsoft DevLabs is taking longer than expected to load.Learn More about this extension, including available support options.

Can't load calender in team service.

**Comment by CCollinsAZ** [comment]
Receive this error when we migrated to https.

**Comment by ruturaj-h** [comment]
Can you provide some more information? If you are on hosted or onpremise version? Error messeage if any on console (right click on browswer window, select inspect, refresh the webpage, check console for any errors).

**Comment by ccollins1973** [comment]
on-prem. We were using http for years, recently enabled https and received the error repeatedly.  Tried uninstalling and reinstalling with https URL (made a difference in the error), still didn't resolve the issue.   However, since you asked about it, it recently stopped.  Unable to reproduce now, so thank you for asking about it.

**Comment by ruturaj-h** [comment]
Thank you for getting back. Glad it worked out for you.
